const STYLES = [
  "sinematik",
  "fotoğrafik",
  "yağlı boya",
  "sulu boya",
  "dijital sanat",
  "siberpunk",
  "fantastik illüstrasyon",
  "minimalist",
  "vintage film",
  "ultra detaylı",
  "anime tarzı",
  "gerçeküstü",
];

const SUBJECTS = [
  "dağ manzarası",
  "okyanus dalgaları",
  "gece şehir silüeti",
  "sisli orman patikası",
  "çöl kumulları",
  "kuzey ışıkları",
  "antik tapınak",
  "modern mimari bina",
  "sakin göl yansıması",
  "volkanik krater",
  "buzul vadisi",
  "tropikal ada",
  "yağmur sonrası şehir",
  "eski köprü",
  "çiçek bahçesi",
  "sonbahar yaprakları",
  "karlı dağ zirvesi",
  "çöl yolu",
  "fıskiyeli meydan",
  "gökyüzünde balonlar",
  "sakin kütüphane içi",
  "loş kafe ortamı",
  "japon bahçesi",
  "vintage araba",
  "motosiklet yolculuğu",
  "deniz feneri",
  "kırsal çiftlik evi",
  "gökdelen terası",
  "metro istasyonu",
  "antik harabe",
  "kristal mağara",
  "uzay istasyonu",
  "gezegen yüzeyi",
  "derin uzay nebulası",
  "robot ve insan",
  "ejderha ve kale",
  "elf savaşçısı",
  "büyücü kulesi",
  "sihirli orman",
  "yüzen ada",
  "denizaltı dünyası",
  "mercan resifi",
  "tropikal yağmur ormanı",
  "savanada vahşi yaşam",
  "kutup ayısı",
  "aslan portresi",
  "renkli kuş",
  "kedi portresi",
  "at koşusu",
  "balıkçı teknesi",
  "şarap bağları",
  "kahve fincanı ve kitap",
  "pasta ve mum ışığı",
  "meyve tabağı",
  "sushi tabağı",
  "pizza dilimi",
  "çikolata parçaları",
  "moda modeli portresi",
  "gelinlik tasarımı",
  "streetwear kombin",
  "vintage moda pozu",
  "dans eden figür",
  "müzisyen sahne performansı",
  "gitar çalan sanatçı",
  "piyano konseri",
  "bale dansçısı",
  "grafiti duvar sanatı",
  "heykel atölyesi",
  "seramik atölyesi",
  "cam sanatı",
  "origami figür",
  "origami kuşlar",
  "mandalalar",
  "geometrik desen",
  "soyut renk patlaması",
  "ışık ve gölge oyunu",
  "mermer yüzey dokusu",
  "ahşap oyma detay",
  "deri dokusu",
  "metal yüzey yansıması",
  "cam kırılması",
  "su damlacıkları",
  "çiy taneleri yaprakta",
  "gökkuşağı",
  "yıldızlı gece",
  "ay ışığı sahili",
  "gün batımı sahili",
  "şafak vakti dağ",
  "sisli sabah köy",
  "yağmur damlaları camda",
  "kar taneleri",
  "buz kristalleri",
  "çöl gecesi kamp",
  "kamp ateşi",
  "dağ evi",
  "ahşap köprü",
  "nehir kıyısı",
  "kayalık sahil",
  "dalga kırılması",
  "sörfçü",
  "kayakçı",
  "dağ bisikletçisi",
  "yoga meditasyon",
  "spa ve wellness",
  "aromaterapi ortamı",
  "zen bahçe",
  "bonsai ağacı",
  "lavanta tarlası",
  "güneş çiçeği tarlası",
  "papatya tarlası",
  "kiraz çiçekleri",
  "sonbahar orman yolu",
  "ilkbahar nehir kenarı",
  "yaz plaj günü",
  "kış kasabası",
  "noel ışıkları",
  "cadılar bayramı dekor",
  "yılbaşı ağacı",
  "festival ışıkları",
  "konser ışık gösterisi",
  "stadyum atmosferi",
  "futbol maçı anı",
  "basketbol sahası",
  "tenis kortu",
  "yüzme havuzu",
  "jimnastik salonu",
  "fitness motivasyon",
  "koşu parkuru",
  "maraton anı",
  "dağ tırmanışı",
  "kayak pisti",
  "snowboard hareketi",
  "buz pateni",
  "paten parkı",
  "skateboard hareketi",
  "BMX bisiklet",
  "motokros",
  "yarış arabası",
  "formül 1 pisti",
  "helikopter manzarası",
  "uçak kanadı manzarası",
  "tren yolculuğu",
  "vapur yolculuğu",
  "yat denizde",
  "liman manzarası",
  "köprü altı su yansıması",
  "tünel ışıkları",
  "neon tabela sokak",
  "gece pazarı",
  "sokak satıcısı",
  "çarşı atmosferi",
  "antika pazar",
  "kitapçı içi",
  "müze galerisi",
  "sanat galerisi",
  "opera binası",
  "tiyatro sahnesi",
  "sinema salonu",
  "film seti",
  "stüdyo ışıkları",
  "fotoğraf stüdyosu",
  "makyaj masası",
  "kuaför salonu",
  "berber dükkanı",
  "pastane vitrin",
  "fırın içi",
  "restoran masa düzeni",
  "bar tezgahı",
  "kokteyl hazırlama",
  "kahve demleme",
  "çay seremonisi",
  "sushi bar",
  "ramen dükkanı",
  "taco standı",
  "burger restoran",
  "pizza fırını",
  "çikolata fabrikası",
  "çikolata dökümü",
  "bal üretimi",
  "bal reçeli",
  "organik pazar",
  "çiftlik pazarı",
  "organik sebze",
  "meyve bahçesi",
  "zeytin ağacı",
  "palmiye ağacı",
  "kaktüs çölü",
  "savan ormanı",
  "mangrov ormanı",
  "bataklık atmosferi",
  "volkanik ada",
  "geyser patlaması",
  "mağara keşfi",
  "mağara içi ışık",
  "kanyon derinliği",
  "şelale manzarası",
  "nehir deltası",
  "delta uçurumu",
  "kıyı kayalıkları",
  "falez manzarası",
  "ada manzarası",
  "lagün suyu",
  "turkuaz deniz",
  "derin mavi okyanus",
  "buzdağı",
  "buzul parçası",
  "kutup manzarası",
  "eskimo köyü",
  "iglo yapısı",
  "kuzey kabilesi",
  "maori sanatı",
  "afrika kabile deseni",
  "hint mandala",
  "japon ukiyo-e",
  "çin kaligrafi",
  "kore hanok evi",
  "tayland tapınağı",
  "vietnam pirinç tarlası",
  "endonezya tapınağı",
  "hindistan sarayı",
  "mısır piramitleri",
  "roma koloseum",
  "atina parthenon",
  "istanbul silüeti",
  "kapadokya balonları",
  "efes harabeleri",
  "pamukkale travertenleri",
  "antalya koyu",
  "bodrum marina",
  "izmir sahil",
  "ankara şehir",
  "bursa yeşil",
  "trabzon yaylası",
  "karadeniz fırtınası",
  "akdeniz güneşi",
  "ege ada manzarası",
  "marmara köprüsü",
  "galata kulesi",
  "ayasofya içi",
  "sultanahmet meydanı",
  "topkapı sarayı",
  "dolmabahçe sarayı",
  "sumela manastırı",
  "nemrut dağı",
  "göbeklitepe",
  "antik tiyatro",
  "roma hamamı",
  "bizans mozaik",
  "osmanlı çini",
  "el işi halı",
  "kilim deseni",
  "çini desen",
  "hat sanatı",
  "ebru sanatı",
  "tezhip detay",
  "minyatür resim",
  "kalemişi desen",
  "ahşap oymacılık",
  "ciltçilik atölyesi",
  "deri işleme",
  "cam üfleme",
  "seramik fırını",
  "çömlek atölyesi",
  "dokuma tezgahı",
  "ipek kumaş",
  "kaşmir dokuma",
  "yün örgü",
  "deri ceket",
  "kot pantolon",
  "sneaker koleksiyonu",
  "saat koleksiyonu",
  "gözlük modası",
  "takı tasarımı",
  "yüzük koleksiyonu",
  "kolye tasarımı",
  "küpe tasarımı",
  "saç stili",
  "makyaj sanatı",
  "nail art",
  "cilt bakımı",
  "parfüm şişesi",
  "kozmetik ürün",
  "spa masajı",
  "hamam atmosferi",
  "türk hamamı",
  "sauna ortamı",
  "jakuzi keyfi",
  "havuz kenarı",
  "plaj şezlong",
  "güneş kremi",
  "plaj voleybolu",
  "sörf tahtası",
  "kano kürek",
  "yelkenli tekne",
  "balık tutma",
  "dalış kıyafeti",
  "snorkel deniz",
  "deniz yıldızı",
  "denizanası",
  "yunus gösterisi",
  "balina gözlemi",
  "penguen kolonisi",
  "kutup kartalı",
  "flamingo grubu",
  "papağan renkleri",
  "tukan kuşu",
  "kolibri uçuşu",
  "kelebek bahçesi",
  "arı kovanı",
  "çiçek tozu",
  "polen detayı",
  "mikroskop görüntü",
  "hücre yapısı",
  "dna helix",
  "laboratuvar ortamı",
  "kimya deneyi",
  "fizik deneyi",
  "robotik atölye",
  "3D yazıcı",
  "lazer kesim",
  "CNC makine",
  "fabrika üretim",
  "otomasyon hattı",
  "depo lojistik",
  "konteyner gemisi",
  "yük treni",
  "kamyon yolculuğu",
  "otobüs terminali",
  "havaalanı terminali",
  "güvenlik kontrol",
  "pilot kokpiti",
  "kontrol kulesi",
  "radar ekranı",
  "uydu görüntüsü",
  "harita detayı",
  "navigasyon cihazı",
  "GPS yolculuk",
  "drone uçuşu",
  "drone manzarası",
  "VR headset",
  "AR gözlük",
  "hologram ekran",
  "touchscreen tablet",
  "akıllı telefon",
  "laptop çalışma",
  "gaming setup",
  "RGB ışıklar",
  "mekanik klavye",
  "oyun kumandası",
  "konsol oyunu",
  "arcade salonu",
  "pinball makinesi",
  "satranç tahtası",
  "tavla oyunu",
  "kart oyunu",
  "poker masası",
  "casino atmosferi",
  "rulet masası",
  "slot makinesi",
  "piyango bileti",
  "konser bilet",
  "festival bileti",
  "sinema bileti",
  "tiyatro bileti",
  "opera bileti",
  "bale bileti",
  "spor bileti",
  "maraton bileti",
  "yoga bileti",
  "fitness bileti",
  "spa bileti",
  "otel rezervasyon",
  "uçak bileti",
  "tren bileti",
  "otobüs bileti",
  "gemi bileti",
  "otel odası",
  "suite oda",
  "penthouse manzara",
  "bungalov ev",
  "treehouse ev",
  "cam ev",
  "yüzen ev",
  "prefabrik ev",
  "modüler ev",
  "sürdürülebilir ev",
  "güneş paneli ev",
  "rüzgar türbini",
  "hidroelektrik",
  "nükleer santral",
  "termik santral",
  "petrol rafinerisi",
  "gaz istasyonu",
  "elektrik şarj istasyonu",
  "bisiklet şarj",
  "scooter paylaşım",
  "elektrikli araba",
  "hibrit araba",
  "otonom araba",
  "uçan araba konsept",
  "hyperloop tünel",
  "uzay turizmi",
  "ay üssü",
  "mars kolonisi",
  "uzay gemisi",
  "roket fırlatma",
  "uydu fırlatma",
  "ISS istasyonu",
  "astronot portresi",
  "kozmonot kıyafeti",
  "uzay giysisi",
  "rover keşif",
  "mars rover",
  "ay rover",
  "teleskop gözlemi",
  "gözlemevi",
  "planetarium",
  "yıldız haritası",
  "takımyıldızı",
  "galaksi spiral",
  "kara delik",
  "süpernova",
  "meteor yağmuru",
  "göktaşı",
  "kuyruklu yıldız",
  "asteroit",
  "gezegen halkası",
  "jüpiter gökyüzü",
  "satürn halkaları",
  "neptün mavisi",
  "plüton yüzeyi",
  "venüs atmosferi",
  "merkür yüzeyi",
  "güneş patlaması",
  "aurora borealis",
  "aurora australis",
  "kutup ışığı",
  "ekvator tropik",
  "çöl sıcak",
  "buz soğuk",
  "sıcak çöl",
  "soğuk kutup",
  "ılıman iklim",
  "muson yağmuru",
  "tropikal fırtına",
  "hurricane gözü",
  "tornado oluşumu",
  "tsunami dalgası",
  "deprem anı",
  "volkan patlaması",
  "lav akışı",
  "kül bulutu",
  "heyelan",
  "çığ düşüşü",
  "kayalık düşüşü",
  "erosion manzarası",
  "zaman geçişi",
  "mevsim değişimi",
  "dört mevsim",
  "ilkbahar çiçekleri",
  "yaz güneşi",
  "sonbahar renkleri",
  "kış karı",
  "mevsimsel değişim",
];

const MOODS = [
  "dramatik atmosfer",
  "huzurlu ruh hali",
  "enerjik dinamizm",
  "melankolik duygu",
  "epik ölçek",
  "minimal sakinlik",
  "romantik ışık",
  "gizemli hava",
  "nostaljik ton",
  "modern keskinlik",
];

const LIGHTING = [
  "altın saat ışığı",
  "yumuşak gün ışığı",
  "dramatik gölgeler",
  "neon aydınlatma",
  "ay ışığı",
  "arka ışık silüeti",
  "studyo ışıklandırması",
  "doğal diffüz ışık",
  "kontrastlı chiaroscuro",
  "pastel tonlar",
];

const QUALITY = [
  "8K ultra detay",
  "profesyonel fotoğraf kalitesi",
  "yüksek dinamik aralık",
  "keskin odak",
  "sinematik renk derecelendirme",
];

function pick<T>(items: T[]): T {
  return items[Math.floor(Math.random() * items.length)];
}

export function getRandomPrompt(): string {
  const style = pick(STYLES);
  const subject = pick(SUBJECTS);
  const mood = pick(MOODS);
  const lighting = pick(LIGHTING);
  const quality = pick(QUALITY);

  return `${style} tarzında ${subject}, ${mood}, ${lighting}, ${quality}`;
}

export function getRandomPromptCount(): number {
  return STYLES.length * SUBJECTS.length * MOODS.length * LIGHTING.length;
}
